language: python
sudo: false
python:
  - pypy-5.4.1
  - 2.7
  - 3.6
  - 3.5
  - 3.4
install:
  - pip install -U pip setuptools zc.buildout
  - buildout parts=test
script: bin/test -v1j99
cache:
  directories:
    - $HOME/.cache/pip
    - eggs
before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
